-- 코드를 입력하세요
SELECT YEAR(sales_date) AS YEAR,
    MONTH(sales_date) AS MONTH, 
    count(DISTINCT O.USER_ID) AS PUCHASED_USERS, 
    ROUND(count(DISTINCT O.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) AS PUCHASED_RATIO
FROM ONLINE_SALE O
INNER JOIN USER_INFO U
ON U.USER_ID = O.USER_ID
WHERE YEAR(JOINED) = 2021
GROUP BY 1,2
ORDER BY 1,2;