SELECT AI.NAME , AI.DATETIME 
FROM ANIMAL_INS AI
LEFT JOIN ANIMAL_OUTS AO
ON (AI.ANIMAL_ID = AO.ANIMAL_ID)
WHERE AO.ANIMAL_ID IS NULL
ORDER BY AI.DATETIME ASC
LIMIT 3

# SELECT ai.name, ai.datetime 
# FROM animal_ins ai LEFT JOIN animal_outs ao
# ON ai.animal_id = ao.animal_id
# WHERE ao.animal_id IS NULL
# ORDER BY ai.datetime ASC
# LIMIT 3