-- 코드를 입력하세요
# '%[^0-9]%'

# SELECT SUBSTRING(PRODUCT_CODE,PATINDEX('%[^0-9]%',PRODUCT_CODE),5) AS PRODUCT_CODE
# FROM PRODUCT

# SELECT PATINDEX('%[^0-9]%',PRODUCT_CODE) FROM PRODUCT
# SELECT SUBSTRING(PRODUCT_CODE,  PatIndex('%[^a-z]%',PRODUCT_CODE),2) AS TEST FROM PRODUCT;

SELECT SUBSTRING(PRODUCT_CODE,1,2) AS CATEGORY, COUNT(PRODUCT_CODE) AS PRODUCTS 
FROM PRODUCT
GROUP BY CATEGORY;