-- 코드를 

-- 트럭 금액 / 7 * 100
SELECT CH.HISTORY_ID, 
ROUND((DATEDIFF(CH.END_DATE,CH.START_DATE)+1) * 
      (CASE
       WHEN DATEDIFF(CH.END_DATE,CH.START_DATE)+1 < 7 THEN 1
        WHEN DATEDIFF(CH.END_DATE,CH.START_DATE)+1 < 30 THEN 0.95
        WHEN DATEDIFF(CH.END_DATE,CH.START_DATE)+1 < 90 THEN 0.92
        ELSE 0.85
    END) * CC.DAILY_FEE,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CC
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
ON(CC.CAR_ID = CH.CAR_ID)
WHERE CC.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC;

# SELECT h.HISTORYID, ROUND((DATEDIFF(h.ENDDATE,h.STARTDATE)+1) *
# (CASE
# WHEN DATEDIFF(h.ENDDATE,h.STARTDATE)+1 < 7 THEN 1
# WHEN DATEDIFF(h.ENDDATE,h.STARTDATE)+1 < 30 THEN 0.95
# WHEN DATEDIFF(h.ENDDATE,h.STARTDATE)+1 < 90 THEN 0.92
# ELSE 0.85
# END) * c.DAILYFEE, 0) AS FEE
# FROM CARRENTALCOMPANYRENTALHISTORY h
# JOIN CARRENTALCOMPANYCAR c ON c.CARID=h.CARID
# WHERE c.CARTYPE='트럭'
# ORDER BY FEE DESC, h.HISTORY_ID DESC